// This file is generated by Firebase Genkit.
// Manual changes will be overwritten - do not edit this file.

'use server';

/**
 * @fileOverview Trash classification AI agent.
 *
 * - classifyTrashFromImage - A function that handles the trash classification process.
 * - ClassifyTrashInput - The input type for the classifyTrashFromImage function.
 * - ClassifyTrashOutput - The return type for the classifyTrashFromImage function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const ClassifyTrashInputSchema = z.object({
  photoDataUri: z
    .string()
    .describe(
      "A photo of a trash item, as a data URI that must include a MIME type and use Base64 encoding. Expected format: 'data:<mimetype>;base64,<encoded_data>'."
    ),
});
export type ClassifyTrashInput = z.infer<typeof ClassifyTrashInputSchema>;

const ClassifyTrashOutputSchema = z.object({
  trashType: z.string().describe('نوع المخلفات في الصورة.'),
  confidence: z
    .number()
    .describe('مستوى الثقة في تصنيف نوع المخلفات (0-1).'),
  disposalInstructions: z
    .string()
    .describe('تعليمات حول كيفية التخلص من المخلفات.'),
});
export type ClassifyTrashOutput = z.infer<typeof ClassifyTrashOutputSchema>;

export async function classifyTrashFromImage(input: ClassifyTrashInput): Promise<ClassifyTrashOutput> {
  return classifyTrashFlow(input);
}

const classifyTrashPrompt = ai.definePrompt({
  name: 'classifyTrashPrompt',
  input: {schema: ClassifyTrashInputSchema},
  output: {schema: ClassifyTrashOutputSchema},
  prompt: `أنت خبير في تصنيف القمامة والتخلص منها.

  بالنظر إلى صورة لأحد المخلفات، ستقوم بتصنيف العنصر وتقديم تعليمات التخلص منه.

  حلل الصورة التالية:
  {{media url=photoDataUri}}

  قم بإرجاع كائن JSON بالحقول التالية:
  - trashType: نوع المخلفات في الصورة (على سبيل المثال، "قارورة بلاستيك"، "صندوق كرتون"، "نفايات طعام").
  - confidence: مستوى الثقة في تصنيف نوع المخلفات (0-1).
  - disposalInstructions: تعليمات حول كيفية التخلص من المخلفات (على سبيل المثال، "إعادة تدوير في الحاوية الزرقاء"، "تحويل إلى سماد في الحاوية الخضراء"، "تخلص منها في الحاوية السوداء").`,
});

const classifyTrashFlow = ai.defineFlow(
  {
    name: 'classifyTrashFlow',
    inputSchema: ClassifyTrashInputSchema,
    outputSchema: ClassifyTrashOutputSchema,
  },
  async input => {
    const {output} = await classifyTrashPrompt(input);
    return output!;
  }
);
