"use client"

import * as React from "react"
import { ThemeProvider as NextThemesProvider } from "next-themes"
import type { ThemeProviderProps } from "next-themes/dist/types"

export function ThemeProvider({ children, ...props }: ThemeProviderProps) {
  return <NextThemesProvider {...props}>{children}</NextThemesProvider>
}


// --- Language Provider ---

type Language = 'ar' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string, options?: { [key: string]: string | number | undefined }) => string;
}

const LanguageContext = React.createContext<LanguageContextType | undefined>(undefined);

const translations: Record<string, Record<Language, string>> = {
  // Common
  'common.actions': { ar: 'الإجراءات', en: 'Actions' },
  'common.status': { ar: 'الحالة', en: 'Status' },
  'common.confirm_action': { ar: 'تأكيد الإجراء', en: 'Confirm Action' },
  'common.cancel': { ar: 'إلغاء', en: 'Cancel' },
  'common.confirm': { ar: 'تأكيد', en: 'Confirm' },
  'common.view_details': { ar: 'عرض التفاصيل', en: 'View Details' },
  'common.approve': { ar: 'موافقة', en: 'Approve' },
  'common.reject': { ar: 'رفض', en: 'Reject' },
  'common.reply': { ar: 'رد', en: 'Reply' },
  'common.print': { ar: 'طباعة', en: 'Print' },
  'common.delete': { ar: 'حذف', en: 'Delete' },
  'common.are_you_sure': { ar: 'هل أنت متأكد؟', en: 'Are you sure?' },
  'common.confirm_delete': { ar: 'تأكيد الحذف', en: 'Confirm Deletion' },
  'common.save': { ar: 'حفظ', en: 'Save' },
  'common.send_reply': { ar: 'إرسال الرد', en: 'Send Reply' },
  'common.close': { ar: 'إغلاق', en: 'Close' },
  'common.send': { ar: 'إرسال', en: 'Send' },
  'common.edit': { ar: 'تعديل', en: 'Edit' },
  'common.approved': { ar: 'تمت الموافقة', en: 'Approved' },
  'common.rejected': { ar: 'تم الرفض', en: 'Rejected' },
  'common.error': { ar: 'خطأ', en: 'Error' },

  // sidebar
  'sidebar.main': { ar: 'الرئيسية', en: 'Dashboard' },
  'sidebar.schedule': { ar: 'جدولة الرفع', en: 'Schedule Pickup' },
  'sidebar.classify': { ar: 'تصنيف المخلفات', en: 'Classify Waste' },
  'sidebar.locations': { ar: 'أماكن الحاويات', en: 'Bin Locations' },
  'sidebar.news': { ar: 'الأخبار', en: 'News' },
  'sidebar.rewards': { ar: 'المكافآت والنقاط', en: 'Rewards & Points' },
  'sidebar.history': { ar: 'السجل والتقارير', en: 'History & Reports' },
  'sidebar.donate': { ar: 'التبرع بالملابس', en: 'Donate Clothes' },
  'sidebar.support': { ar: 'ادعمنا', en: 'Support Us' },
  'sidebar.contact': { ar: 'البلاغات والاقتراحات', en: 'Feedback & Suggestions' },
  'sidebar.help': { ar: 'التعليمات', en: 'Help' },
  // admin sidebar
  'sidebar.admin.title': { ar: 'إدارة النظام', en: 'Admin' },
  'sidebar.admin.dashboard': { ar: 'لوحة التحكم', en: 'Dashboard' },
    'sidebar.admin.map': { ar: 'خريطة منازل الحي', en: 'Residences Map' },
  'sidebar.admin.locations': { ar: 'إدارة مواقع الحاويات', en: 'Manage Bin Locations' },
  'sidebar.admin.users': { ar: 'إدارة المستخدمين', en: 'Manage Users' },
  'sidebar.admin.points': { ar: 'إدارة النقاط', en: 'Manage Points' },
  'sidebar.admin.vouchers': { ar: 'إدارة القسائم', en: 'Manage Vouchers' },
  'sidebar.admin.donations': { ar: 'إدارة التبرعات', en: 'Manage Donations' },
  'sidebar.admin.financial': { ar: 'إدارة الدعم المالي', en: 'Manage Financial Support' },
  'sidebar.admin.redemptions': { ar: 'إدارة طلبات الاستبدال', en: 'Manage Redemptions' },
  'sidebar.admin.schedules': { ar: 'إدارة جداول الرفع', en: 'Manage Pickups' },
  'sidebar.admin.notifications': { ar: 'إدارة الإشعارات', en: 'Manage Notifications' },
  'sidebar.admin.feedback': { ar: 'إدارة البلاغات', en: 'Manage Feedback' },
  'sidebar.admin.news': { ar: 'إدارة الأخبار', en: 'Manage News' },
  'sidebar.admin.reports': { ar: 'تقارير النظام', en: 'System Reports' },
  // bottom nav
  'bottomnav.dashboard': { ar: 'الرئيسية', en: 'Home' },
  'bottomnav.schedule': { ar: 'جدولة', en: 'Schedule' },
  'bottomnav.classify': { ar: 'تصنيف', en: 'Classify' },
  'bottomnav.news': { ar: 'الأخبار', en: 'News' },
  'bottomnav.contact': { ar: 'البلاغات', en: 'Feedback' },
  // header
  'header.welcome': { ar: 'أهلاً بك', en: 'Welcome' },
  // user menu
  'usermenu.my_account': { ar: 'حسابي', en: 'My Account' },
  'usermenu.view_account': { ar: 'عرض الحساب', en: 'View Account' },
  'usermenu.settings': { ar: 'الإعدادات', en: 'Settings' },
  'usermenu.logout': { ar: 'تسجيل الخروج', en: 'Log Out' },
  'usermenu.login': { ar: 'تسجيل الدخول', en: 'Log In' },
  'usermenu.register': { ar: 'تسجيل', en: 'Register' },
  'usermenu.visitor': { ar: 'زائر', en: 'Visitor' },
  // logout dialog
  'logout_dialog.title': { ar: 'هل أنت متأكد؟', en: 'Are you sure?' },
  'logout_dialog.description': { ar: 'هل تريد حقًا تسجيل الخروج من حسابك؟', en: 'Do you really want to log out?' },
  'logout_dialog.cancel': { ar: 'إلغاء', en: 'Cancel' },
  'logout_dialog.confirm': { ar: 'تأكيد', en: 'Confirm' },

  // profile page
  'profile.title': { ar: 'إعدادات الحساب', en: 'Account Settings' },
  'profile.description': { ar: 'إدارة ملفك الشخصي، العنوان، وتفضيلات الأمان.', en: 'Manage your profile, address, and security preferences.' },
  'profile.tabs.profile': { ar: 'الملف الشخصي', en: 'Profile' },
  'profile.tabs.address': { ar: 'العنوان', en: 'Address' },
  'profile.tabs.security': { ar: 'الأمان', en: 'Security' },
  'profile.tabs.appearance': { ar: 'المظهر', en: 'Appearance' },
  'profile.tabs.account': { ar: 'الحساب', en: 'Account' },
  
  'profile.personal.title': { ar: 'معلوماتك الشخصية', en: 'Personal Information' },
  'profile.personal.description': { ar: 'تحديث بياناتك الشخصية وصورتك الرمزية.', en: 'Update your personal data and avatar.' },
  'profile.personal.full_name': { ar: 'الاسم الكامل', en: 'Full Name' },
  'profile.personal.phone': { ar: 'رقم الهاتف', en: 'Phone Number' },
  'profile.personal.email': { ar: 'البريد الإلكتروني', en: 'Email Address' },
  'profile.personal.save_button': { ar: 'حفظ التغييرات', en: 'Save Changes' },

  'profile.address.title': { ar: 'العنوان والموقع', en: 'Address & Location' },
  'profile.address.description': { ar: 'إدارة عنوانك وموقعك على الخريطة لتسهيل عملية الرفع.', en: 'Manage your address and map location to facilitate pickups.' },
  'profile.address.address_details': { ar: 'عنوان المنزل التفصيلي', en: 'Detailed Home Address' },
  'profile.address.landmark': { ar: 'أقرب معلم (اختياري)', en: 'Nearest Landmark (Optional)' },
  'profile.address.coordinates': { ar: 'الإحداثيات', en: 'Coordinates' },
  'profile.address.coordinates_placeholder': { ar: 'محدد من الخريطة', en: 'Set from map' },
  'profile.address.save_button': { ar: 'حفظ العنوان', en: 'Save Address' },

  'profile.security.title': { ar: 'الأمان وكلمة المرور', en: 'Security & Password' },
  'profile.security.description': { ar: 'تغيير كلمة المرور الخاصة بك بشكل دوري للحفاظ على أمان حسابك.', en: 'Change your password periodically to keep your account secure.' },
  'profile.security.current_password': { ar: 'كلمة المرور الحالية', en: 'Current Password' },
  'profile.security.new_password': { ar: 'كلمة المرور الجديدة', en: 'New Password' },
  'profile.security.confirm_password': { ar: 'تأكيد كلمة المرور الجديدة', en: 'Confirm New Password' },
  'profile.security.save_button': { ar: 'تغيير كلمة المرور', en: 'Change Password' },

  'profile.appearance.title': { ar: 'المظهر واللغة', en: 'Appearance & Language' },
  'profile.appearance.description': { ar: 'خصص شكل التطبيق ولغته حسب تفضيلاتك.', en: 'Customize the app\'s look and language to your preference.' },
  'profile.appearance.theme': { ar: 'الوضع', en: 'Theme' },
  'profile.appearance.light': { ar: 'فاتح', en: 'Light' },
  'profile.appearance.dark': { ar: 'داكن', en: 'Dark' },
  'profile.appearance.system': { ar: 'النظام', en: 'System' },
  'profile.appearance.language': { ar: 'اللغة', en: 'Language' },
  'profile.appearance.arabic': { ar: 'العربية', en: 'العربية' },
  'profile.appearance.english': { ar: 'English', en: 'English' },
  'profile.appearance.note': { ar: 'ملاحظة: تغيير اللغة سيغير اتجاه النص. الترجمة الكاملة للمحتوى غير مدعومة حاليًا.', en: 'Note: Changing language will change text direction. Full content translation is not currently supported.' },

  'profile.account.title': { ar: 'حذف الحساب', en: 'Delete Account' },
  'profile.account.description': { ar: 'هذا الإجراء سيقوم بحذف حسابك وجميع بياناتك بشكل نهائي. لا يمكن التراجع عن هذا القرار.', en: 'This action will permanently delete your account and all its data. This cannot be undone.' },
  'profile.account.delete_button': { ar: 'أفهم العواقب، قم بحذف حسابي', en: 'I understand the consequences, delete my account' },
  'profile.account.dialog_title': { ar: 'هل أنت متأكد تماماً؟', en: 'Are you absolutely sure?' },
  'profile.account.dialog_description': { ar: 'سيتم حذف حسابك نهائياً بما في ذلك نقاطك وسجلك. لا يمكن استعادة هذه البيانات.', en: 'Your account will be permanently deleted, including your points and history. This data cannot be recovered.' },
  'profile.account.dialog_cancel': { ar: 'إلغاء', en: 'Cancel' },
  'profile.account.dialog_confirm': { ar: 'تأكيد الحذف', en: 'Confirm Deletion' },
  'profile.toast.location_set_title': { ar: 'تم تحديد الموقع', en: 'Location Set' },
  'profile.toast.location_set_desc': { ar: 'تم تحديث الخريطة بموقعك الحالي.', en: 'Map updated with your current location.' },
  'profile.toast.location_error_title': { ar: 'خطأ في تحديد الموقع', en: 'Location Error' },
  'profile.toast.location_error_desc': { ar: 'لا يمكن الوصول إلى موقعك.', en: 'Could not access your location.' },

  'dashboard.welcome': { ar: 'أهلاً بعودتك، {name}!', en: 'Welcome back, {name}!' },
  'dashboard.cards.next_pickup': { ar: 'الرفع القادم', en: 'Next Pickup' },
  'dashboard.cards.tomorrow': { ar: 'غداً', en: 'Tomorrow' },
  'dashboard.cards.pickup_status': { ar: 'حالة الرفع', en: 'Pickup Status' },
  'dashboard.cards.points_earned': { ar: 'النقاط المكتسبة', en: 'Points Earned' },
  'dashboard.cards.points_value': { ar: '{value} نقطة', en: '{value} Points' },
  'dashboard.cards.points_change': { ar: '+{value} من آخر عملية', en: '+{value} since last activity' },
  'dashboard.cards.notifications': { ar: 'إشعارات وتنبيهات', en: 'Notifications & Alerts' },
  'dashboard.notifications.title1': { ar: 'نصيحة اليوم', en: 'Tip of the Day' },
  'dashboard.notifications.content1': { ar: 'يمكن إعادة تدوير علب الألمنيوم بلا حدود. لا ترمها!', en: 'Aluminum cans are infinitely recyclable. Don\'t trash them!' },
  'dashboard.notifications.title2': { ar: 'تحديث المجتمع', en: 'Community Update' },
  'dashboard.notifications.content2': { ar: 'تم جمع أكثر من 500 كجم من البلاستيك هذا الأسبوع!', en: 'Over 500kg of plastic collected this week!' },
  'dashboard.notifications.title3': { ar: 'تذكير بالجمع', en: 'Pickup Reminder' },
  'dashboard.notifications.content3': { ar: 'جمع النفايات العضوية مقرر غداً صباحاً.', en: 'Organic waste pickup is scheduled for tomorrow morning.' },
  'dashboard.notifications.title4': { ar: 'شريك جديد', en: 'New Partner' },
  'dashboard.notifications.content4': { ar: 'استبدل نقاطك لدى "المتجر الأخضر" الآن!', en: 'Redeem your points at "The Green Store" now!' },
  'dashboard.actions.schedule_title': { ar: 'جدولة رفع جديد', en: 'Schedule a New Pickup' },
  'dashboard.actions.schedule_desc': { ar: 'هل لديك مواد لإعادة التدوير؟ حدد موعدًا وسنأتي إليك.', en: 'Have items to recycle? Set a date and we\'ll come to you.' },
  'dashboard.actions.schedule_button': { ar: 'اطلب رفع الآن', en: 'Request a Pickup' },
  'dashboard.actions.classify_title': { ar: 'تصنيف المخلفات بالذكاء الاصطناعي', en: 'Classify Waste with AI' },
  'dashboard.actions.classify_desc': { ar: 'لست متأكدًا من نوع المخلفات؟ التقط صورة ودعنا نساعدك.', en: 'Not sure about a waste type? Snap a picture and let us help.' },
  'dashboard.actions.classify_button': { ar: 'صنف الآن', en: 'Classify Now' },
  'dashboard.report.title': { ar: 'تقريرك الشهري', en: 'Your Monthly Report' },
  'dashboard.report.description': { ar: 'نظرة عامة على مساهماتك هذا الشهر.', en: 'An overview of your contributions this month.' },
  'dashboard.impact.title': { ar: 'أثرك البيئي', en: 'Your Environmental Impact' },
  'dashboard.impact.description': { ar: 'شاهد كيف تساهم في حماية الكوكب.', en: 'See how you\'re helping protect the planet.' },
  'dashboard.impact.trees_saved': { ar: '{count} شجرة تم إنقاذها', en: '{count} Trees Saved' },
  'dashboard.impact.trees_desc': { ar: 'من خلال إعادة تدوير الورق.', en: 'By recycling paper products.' },
  'dashboard.impact.co2_reduced': { ar: 'خفض {value} كجم من CO2', en: '{value}kg of CO2 Reduced' },
  'dashboard.impact.co2_desc': { ar: 'ما يعادل قيادة سيارة لمسافة {value} كم.', en: 'Equivalent to driving {value}km.' },
  'dashboard.links.rewards_title': { ar: 'المكافآت والقسائم', en: 'Rewards & Vouchers' },
  'dashboard.links.rewards_desc': { ar: 'استبدل نقاطك بجوائز قيمة.', en: 'Redeem your points for valuable prizes.' },
  'dashboard.links.history_title': { ar: 'سجل الرفع الخاص بك', en: 'Your Pickup History' },
  'dashboard.links.history_desc': { ar: 'تتبع جميع عمليات الرفع السابقة.', en: 'Track all your past pickups.' },

  'collection.status.collected': { ar: 'تم الرفع', en: 'Collected' },
  'collection.status.scheduled': { ar: 'مجدول', en: 'Scheduled' },
  'collection.status.missed': { ar: 'مفقود', en: 'Missed' },
  'collection.status.you': { ar: 'أنت', en: 'You' },
  'collection.type.recycling': { ar: 'إعادة تدوير', en: 'Recycling' },
  'collection.type.general': { ar: 'نفايات عامة', en: 'General Waste' },
  'collection.type.organic': { ar: 'نفايات عضوية', en: 'Organic Waste' },
    'admin.points.manage_badges': { ar: 'إدارة الشارات', en: 'Manage Badges' },
    'admin.points.dialog.manage_badges_title': { ar: 'إدارة شارات {name}', en: 'Manage Badges for {name}' },
    'admin.points.dialog.manage_badges_desc': { ar: 'عرض وسحب الشارات الممنوحة للمستخدم.', en: 'View and revoke badges granted to the user.' },
    'admin.points.revoke_badge': { ar: 'سحب', en: 'Revoke' },
    'admin.points.confirm_revoke': { ar: 'تأكيد سحب الشارة', en: 'Confirm Badge Revocation' },
    'admin.points.confirm_revoke_desc': { ar: 'هل تريد حقًا سحب شارة "{badgeName}" من هذا المستخدم؟', en: 'Do you really want to revoke the "{badgeName}" badge from this user?' },
    'admin.points.no_badges_to_manage': { ar: 'لا يملك المستخدم أي شارات لإدارتها.', en: 'The user has no badges to manage.' },

  'admin.dashboard.title': { ar: 'لوحة تحكم المسؤول', en: 'Admin Dashboard' },
  'admin.dashboard.description': { ar: 'نظرة عامة وإدارة شاملة للنظام.', en: 'Overview and comprehensive system management.' },
  'admin.dashboard.card.users_desc': { ar: 'إدارة حسابات المستخدمين وأدوارهم.', en: 'Manage user accounts and roles.' },
  'admin.dashboard.card.points_desc': { ar: 'منح أو خصم النقاط للمستخدمين.', en: 'Grant or deduct points for users.' },
  'admin.dashboard.card.vouchers_desc': { ar: 'إضافة وتعديل قسائم المكافآت.', en: 'Add and edit reward vouchers.' },
  'admin.dashboard.card.notifications_desc': { ar: 'إرسال إشعارات وتنبيهات للمستخدمين.', en: 'Send notifications and alerts to users.' },
  'admin.dashboard.card.feedback_desc': { ar: 'مراجعة البلاغات والشكاوى والاقتراحات.', en: 'Review feedback, complaints, and suggestions.' },
  'admin.dashboard.card.donations_desc': { ar: 'مراجعة وتأكيد طلبات التبرع بالملابس.', en: 'Review and confirm clothing donation requests.' },
  'admin.dashboard.card.financial_desc': { ar: 'مراجعة وتأكيد عمليات الدعم المالي.', en: 'Review and confirm financial support submissions.' },
  'admin.dashboard.card.redemptions_desc': { ar: 'مراجعة طلبات استبدال النقاط بمبالغ.', en: 'Review requests to redeem points for cash.' },
  'admin.dashboard.card.schedules_desc': { ar: 'مراجعة وتعديل جداول جمع النفايات.', en: 'Review and edit waste collection schedules.' },
  'admin.dashboard.card.map_desc': { ar: 'عرض وإدارة مواقع المنازل على الخريطة.', en: 'View and manage house locations on the map.' },
  'admin.dashboard.card.locations_desc': { ar: 'إدارة مواقع الحاويات العامة في الأحياء.', en: 'Manage public bin locations in neighborhoods.' },
  'admin.dashboard.card.reports_desc': { ar: 'عرض تقارير وبيانات أداء النظام.', en: 'View system performance reports and data.' },
    'admin.dashboard.card.news_desc': { ar: 'إنشاء وتعديل وحذف المقالات والأخبار.', en: 'Create, edit, and delete articles and news.' },

  'admin.donations.title': { ar: 'إدارة تبرعات الملابس', en: 'Manage Clothing Donations' },
  'admin.donations.description': { ar: 'مراجعة طلبات التبرع وتحديث حالتها.', en: 'Review donation requests and update their status.' },
  'admin.donations.table.id': { ar: 'المعرف', en: 'ID' },
  'admin.donations.table.donor': { ar: 'المتبرع', en: 'Donor' },
  'admin.donations.table.type_condition': { ar: 'النوع والحالة', en: 'Type & Condition' },
  'admin.donations.table.quantity': { ar: 'الكمية', en: 'Quantity' },
  'donations.quantity_piece': { ar: '{quantity} قطعة', en: '{quantity} pieces' },
  'donations.status.pending': { ar: 'معلق', en: 'Pending' },
  'donations.status.approved': { ar: 'مقبول', en: 'Approved' },
  'donations.status.received': { ar: 'تم الاستلام', en: 'Received' },
  'donations.status.rejected': { ar: 'مرفوض', en: 'Rejected' },
  'donations.type.female': { ar: 'نسائي', en: 'Women\'s' },
  'donations.type.kids': { ar: 'أطفال', en: 'Kids\'' },
  'donations.type.male': { ar: 'رجالي', en: 'Men\'s' },
  'donations.type.mixed': { ar: 'مختلط', en: 'Mixed' },
  'donations.condition.new': { ar: 'جديدة', en: 'New' },
  'donations.condition.used_good': { ar: 'مستخدمة (بحالة جيدة)', en: 'Used (Good Condition)' },
  'donations.action.dispatch': { ar: 'إرسال مندوب', en: 'Dispatch Agent' },
  'donations.confirm.approve': { ar: 'هل أنت متأكد أنك تريد الموافقة على التبرع رقم {id} من {user}؟', en: 'Are you sure you want to approve donation #{id} from {user}?' },
  'donations.confirm.reject': { ar: 'هل أنت متأكد أنك تريد رفض التبرع رقم {id} من {user}؟', en: 'Are you sure you want to reject donation #{id} from {user}?' },
  'donations.confirm.dispatch': { ar: 'هل أنت متأكد من إرسال مندوب لاستلام التبرع رقم {id}؟', en: 'Are you sure you want to dispatch an agent to collect donation #{id}?' },

    'admin.landmarks.manage_title': { ar: 'إدارة المعالم', en: 'Manage Landmarks' },
    'admin.landmarks.manage_desc': { ar: 'إضافة وتعديل وحذف المعالم الهامة على الخريطة.', en: 'Add, edit, and delete important landmarks on the map.' },
    'admin.landmarks.add_new': { ar: 'إضافة معلم جديد', en: 'Add New Landmark' },
    'admin.landmarks.table.name': { ar: 'اسم المعلم', en: 'Landmark Name' },
    'admin.landmarks.table.type': { ar: 'نوع المعلم', en: 'Landmark Type' },
    'admin.landmarks.dialog.add_title': { ar: 'إضافة معلم جديد', en: 'Add New Landmark' },
    'admin.landmarks.dialog.edit_title': { ar: 'تعديل معلم', en: 'Edit Landmark' },
    'admin.landmarks.form.name': { ar: 'اسم المعلم', en: 'Landmark Name' },
    'admin.landmarks.form.type': { ar: 'نوع المعلم', en: 'Landmark Type' },
    'admin.landmarks.form.type_placeholder': { ar: 'اختر نوعًا...', en: 'Select a type...' },
    'admin.landmarks.type.mosque': { ar: 'مسجد', en: 'Mosque' },
    'admin.landmarks.type.hospital': { ar: 'مستشفى', en: 'Hospital' },
    'admin.landmarks.type.school': { ar: 'مدرسة', en: 'School' },
    'admin.landmarks.type.park': { ar: 'حديقة', en: 'Park' },
    'admin.landmarks.toast.added': { ar: 'تمت إضافة المعلم بنجاح', en: 'Landmark added successfully' },
    'admin.landmarks.toast.updated': { ar: 'تم تحديث المعلم بنجاح', en: 'Landmark updated successfully' },
    'admin.landmarks.toast.deleted': { ar: 'تم حذف المعلم بنجاح', en: 'Landmark deleted successfully' },
    'admin.landmarks.confirm_delete': { ar: 'هل تريد حقًا حذف المعلم "{name}"؟', en: 'Do you really want to delete the landmark "{name}"?' },

    'admin.drivers.title': { ar: 'إدارة السائقين', en: 'Manage Drivers' },
    'admin.drivers.description': { ar: 'إضافة وتعديل وحذف بيانات السائقين في النظام.', en: 'Add, edit, and delete driver data in the system.' },
    'admin.drivers.add_new': { ar: 'إضافة سائق جديد', en: 'Add New Driver' },
    'admin.drivers.table.name': { ar: 'اسم السائق', en: 'Driver Name' },
    'admin.drivers.table.phone': { ar: 'رقم الهاتف', en: 'Phone Number' },
    'admin.drivers.dialog.add_title': { ar: 'إضافة سائق جديد', en: 'Add New Driver' },
    'admin.drivers.dialog.edit_title': { ar: 'تعديل بيانات سائق', en: 'Edit Driver Data' },
    'admin.drivers.form.name': { ar: 'الاسم الكامل للسائق', en: 'Driver\'s Full Name' },
    'admin.drivers.form.phone': { ar: 'رقم هاتف السائق', en: 'Driver\'s Phone Number' },
    'admin.drivers.toast.added': { ar: 'تمت إضافة السائق بنجاح', en: 'Driver added successfully' },
    'admin.drivers.toast.updated': { ar: 'تم تحديث السائق بنجاح', en: 'Driver updated successfully' },
    'admin.drivers.toast.deleted': { ar: 'تم حذف السائق بنجاح', en: 'Driver deleted successfully' },
    'admin.drivers.confirm_delete': { ar: 'هل تريد حقًا حذف السائق {name}؟', en: 'Do you really want to delete the driver {name}?' },

  'admin.feedback.title': { ar: 'إدارة البلاغات والآراء', en: 'Manage Feedback' },
  'admin.feedback.description': { ar: 'مراجعة بلاغات المستخدمين، شكاواهم، واقتراحاتهم.', en: 'Review user reports, complaints, and suggestions.' },
  'admin.feedback.table.id': { ar: 'المعرف', en: 'ID' },
  'admin.feedback.table.type': { ar: 'النوع', en: 'Type' },
  'admin.feedback.table.subject': { ar: 'الموضوع', en: 'Subject' },
  'admin.feedback.table.date': { ar: 'التاريخ', en: 'Date' },
  'admin.feedback.table.status': { ar: 'الحالة', en: 'Status' },
  'feedback.type.report': { ar: 'بلاغ', en: 'Report' },
  'feedback.type.complaint': { ar: 'شكوى', en: 'Complaint' },
  'feedback.type.suggestion': { ar: 'اقتراح', en: 'Suggestion' },
  'feedback.status.new': { ar: 'جديد', en: 'New' },
  'feedback.status.in_review': { ar: 'قيد المراجعة', en: 'In Review' },
  'feedback.status.resolved': { ar: 'تم الحل', en: 'Resolved' },
  'feedback.actions_label': { ar: 'الإجراءات', en: 'Actions' },
  'feedback.view_details': { ar: 'عرض التفاصيل', en: 'View Details' },
  'feedback.change_to_in_review': { ar: 'تغيير إلى "قيد المراجعة"', en: 'Change to "In Review"' },
  'feedback.change_to_resolved': { ar: 'تغيير إلى "تم الحل"', en: 'Change to "Resolved"' },
  'feedback.sheet.sent_by': { ar: 'مرسل من {user} في تاريخ {date}', en: 'Sent by {user} on {date}' },
  'feedback.sheet.message_details': { ar: 'تفاصيل الرسالة', en: 'Message Details' },
  'feedback.sheet.attachment': { ar: 'المرفق', en: 'Attachment' },
  'feedback.confirm_delete': { ar: 'سيتم حذف هذا البلاغ بشكل نهائي. لا يمكن التراجع عن هذا الإجراء.', en: 'This feedback will be permanently deleted. This action cannot be undone.' },
  'feedback.reply_to': { ar: 'الرد على {user}', en: 'Reply to {user}' },
  'feedback.reply_desc': { ar: 'سيتم إرسال ردك مباشرة إلى المستخدم عبر إشعارات التطبيق.', en: 'Your reply will be sent directly to the user via in-app notifications.' },
  'feedback.reply_placeholder': { ar: 'اكتب ردك هنا...', en: 'Type your reply here...' },
  'feedback.toast.deleted': { ar: 'تم حذف البلاغ بنجاح', en: 'Feedback deleted successfully' },
  'feedback.toast.reply_sent': { ar: 'تم إرسال الرد بنجاح', en: 'Reply sent successfully' },
  'feedback.toast.dev_title': { ar: 'الميزة قيد التطوير', en: 'Feature in Development' },
  'feedback.toast.dev_desc': { ar: 'خيار الطباعة غير متوفر حاليًا.', en: 'The print option is not available yet.' },

  'admin.financial_support.title': { ar: 'إدارة الدعم المالي', en: 'Manage Financial Support' },
  'admin.financial_support.description': { ar: 'مراجعة إثباتات الدعم المالي وتأكيدها.', en: 'Review and confirm financial support proofs.' },
  'admin.financial_support.table.id': { ar: 'المعرف', en: 'ID' },
  'admin.financial_support.table.donor': { ar: 'الداعم', en: 'Donor' },
  'admin.financial_support.table.amount_bank': { ar: 'المبلغ والبنك', en: 'Amount & Bank' },
  'admin.financial_support.table.date': { ar: 'التاريخ', en: 'Date' },
  'support.amount_in_currency': { ar: '{amount} ريال', en: '{amount} YER' },
  'support.status.in_review': { ar: 'قيد المراجعة', en: 'In Review' },
  'support.status.approved': { ar: 'مقبول', en: 'Approved' },
  'support.status.rejected': { ar: 'مرفوض', en: 'Rejected' },
  'support.sheet.title': { ar: 'تفاصيل الدعم #{id}', en: 'Support Details #{id}' },
  'support.sheet.sent_by': { ar: 'مرسل من {donorName} في تاريخ {date}', en: 'Sent by {donorName} on {date}' },
  'support.sheet.support_data': { ar: 'بيانات الدعم', en: 'Support Data' },
  'support.sheet.donor': { ar: 'الداعم', en: 'Donor' },
  'support.sheet.amount': { ar: 'المبلغ', en: 'Amount' },
  'support.sheet.bank': { ar: 'البنك', en: 'Bank' },
  'support.sheet.status': { ar: 'الحالة', en: 'Status' },
  'support.sheet.receipt': { ar: 'إيصال التحويل', en: 'Transfer Receipt' },

  'admin.locations.title': { ar: 'إدارة مواقع الحاويات', en: 'Manage Bin Locations' },
  'admin.locations.description': { ar: 'إضافة وتعديل مواقع الحاويات العامة على الخريطة.', en: 'Add and edit public bin locations on the map.' },
  'admin.locations.add_new': { ar: 'إضافة موقع جديد', en: 'Add New Location' },
  'admin.locations.table.name': { ar: 'اسم الموقع', en: 'Location Name' },
  'admin.locations.table.lat': { ar: 'خط العرض', en: 'Latitude' },
  'admin.locations.table.lng': { ar: 'خط الطول', en: 'Longitude' },
  'admin.locations.dialog.edit_title': { ar: 'تعديل موقع حاوية', en: 'Edit Bin Location' },
  'admin.locations.dialog.add_title': { ar: 'إضافة موقع حاوية جديد', en: 'Add New Bin Location' },
  'admin.locations.form.name_label': { ar: 'اسم الموقع', en: 'Location Name' },
  'admin.locations.form.link_label': { ar: 'رابط خرائط جوجل (اختياري)', en: 'Google Maps Link (Optional)' },
  'admin.locations.form.lat_label': { ar: 'خط العرض', en: 'Latitude' },
  'admin.locations.form.lng_label': { ar: 'خط الطول', en: 'Longitude' },
  'admin.locations.confirm_delete': { ar: 'سيؤدي هذا إلى حذف الموقع "{name}" نهائيًا.', en: 'This will permanently delete the location "{name}".' },
  'admin.locations.toast.updated': { ar: 'تم تحديث الموقع بنجاح', en: 'Location updated successfully' },
  'admin.locations.toast.added': { ar: 'تمت إضافة الموقع بنجاح', en: 'Location added successfully' },
  'admin.locations.toast.deleted': { ar: 'تم حذف الموقع بنجاح', en: 'Location deleted successfully' },

  'admin.map.title': { ar: 'خريطة منازل الحي', en: 'Neighborhood Residences Map' },
  'admin.map.description': { ar: 'عرض حالة الجمع لجميع المنازل المسجلة في الحي.', en: 'View collection status for all registered houses in the neighborhood.' },
  'admin.map.house_tooltip': { ar: 'منزل رقم', en: 'House #' },
  'admin.map.legend_title': { ar: 'مفتاح الخريطة', en: 'Map Legend' },
  'admin.map.legend.collected': { ar: 'تم الرفع', en: 'Collected' },
  'admin.map.legend.scheduled': { ar: 'مجدول', en: 'Scheduled' },
  'admin.map.legend.missed': { ar: 'مفقود', en: 'Missed' },
  'admin.map.legend.truck': { ar: 'شاحنة جمع', en: 'Collection Truck' },
  'admin.map.legend.report': { ar: 'بلاغ عن تكدس', en: 'Dumping Report' },
  'admin.map.sheet.title': { ar: 'تفاصيل المنزل رقم {number}', en: 'Details for House #{number}' },
  'admin.map.sheet.description': { ar: 'معلومات عن الساكن وحالة جمع النفايات.', en: 'Information about the resident and waste collection status.' },
  'admin.map.sheet.current_resident': { ar: 'الساكن الحالي', en: 'Current Resident' },
  'admin.map.sheet.status': { ar: 'الحالة', en: 'Status' },
  'admin.map.sheet.last_collected_type': { ar: 'آخر نوع تم جمعه', en: 'Last Type Collected' },
  'admin.map.sheet.last_collection_date': { ar: 'تاريخ آخر جمع', en: 'Last Collection Date' },
  'admin.map.sheet.location': { ar: 'الموقع على الخريطة', en: 'Location on Map' },
  'admin.map.dialog.edit_title': { ar: 'تعديل بيانات المنزل', en: 'Edit House Data' },
  'admin.map.dialog.edit_desc': { ar: 'تعديل معلومات المنزل والساكن.', en: 'Modify house and resident information.' },
  'admin.map.form.resident_name': { ar: 'اسم الساكن', en: 'Resident Name' },
  'admin.map.confirm_delete': { ar: 'هل تريد حقًا حذف المنزل رقم {number}؟', en: 'Do you really want to delete house #{number}?' },
  'admin.map.toast.updated': { ar: 'تم تحديث بيانات المنزل بنجاح', en: 'House data updated successfully' },
  'admin.map.toast.deleted': { ar: 'تم حذف المنزل بنجاح', en: 'House deleted successfully' },

  'admin.news.title': { ar: 'إدارة الأخبار والمقالات', en: 'Manage News & Articles' },
  'admin.news.description': { ar: 'أنشئ وعدّل المقالات التي تظهر في قسم الأخبار.', en: 'Create and edit articles that appear in the news section.' },
  'admin.news.add_new': { ar: 'إضافة خبر جديد', en: 'Add New Article' },
  'admin.news.table.title': { ar: 'العنوان', en: 'Title' },
  'admin.news.table.author': { ar: 'الكاتب', en: 'Author' },
  'admin.news.table.date': { ar: 'تاريخ النشر', en: 'Publish Date' },
  'admin.news.dialog.edit_title': { ar: 'تعديل الخبر', en: 'Edit Article' },
  'admin.news.dialog.add_title': { ar: 'إضافة خبر جديد', en: 'Add New Article' },
  'admin.news.form.title': { ar: 'العنوان', en: 'Title' },
  'admin.news.form.author': { ar: 'الكاتب', en: 'Author' },
  'admin.news.form.content': { ar: 'المحتوى', en: 'Content' },
  'admin.news.form.content_placeholder': { ar: 'اكتب محتوى الخبر هنا...', en: 'Write the article content here...' },
  'admin.news.confirm_delete': { ar: 'هل تريد حقًا حذف الخبر "{title}"؟', en: 'Do you really want to delete the article "{title}"?' },
  'admin.news.toast.updated': { ar: 'تم تحديث الخبر بنجاح', en: 'Article updated successfully' },
  'admin.news.toast.added': { ar: 'تم نشر الخبر بنجاح', en: 'Article published successfully' },
  'admin.news.toast.deleted': { ar: 'تم حذف الخبر', en: 'Article deleted' },

  'admin.notifications.title': { ar: 'إدارة الإشعارات', en: 'Manage Notifications' },
  'admin.notifications.description': { ar: 'أرسل إشعارات مخصصة للمستخدمين أو للجميع.', en: 'Send custom notifications to users or everyone.' },
  'admin.notifications.send_new': { ar: 'إرسال إشعار جديد', en: 'Send New Notification' },
  'admin.notifications.table.title': { ar: 'العنوان', en: 'Title' },
  'admin.notifications.table.content': { ar: 'المحتوى', en: 'Content' },
  'admin.notifications.table.audience': { ar: 'الجمهور', en: 'Audience' },
  'admin.notifications.table.date': { ar: 'تاريخ الإرسال', en: 'Date Sent' },

    'admin.notifications.audience.all': { ar: 'الكل (بما في ذلك الزوار)', en: 'All (including visitors)' },
    'admin.notifications.audience.users': { ar: 'المستخدمون المسجلون فقط', en: 'Registered Users Only' },
    'admin.notifications.audience.admins': { ar: 'المدراء فقط', en: 'Admins Only' },
    'admin.notifications.audience.specific_user': { ar: 'مستخدم محدد', en: 'Specific User' },

  'admin.notifications.dialog.edit_title': { ar: 'تعديل الإشعار', en: 'Edit Notification' },
  'admin.notifications.dialog.send_title': { ar: 'إرسال إشعار جديد', en: 'Send New Notification' },
  'admin.notifications.form.title': { ar: 'العنوان', en: 'Title' },
  'admin.notifications.form.content': { ar: 'محتوى الإشعار', en: 'Notification Content' },
  'admin.notifications.form.content_placeholder': { ar: 'اكتب رسالتك هنا...', en: 'Type your message here...' },
  'admin.notifications.form.target_audience': { ar: 'الجمهور المستهدف', en: 'Target Audience' },
  'admin.notifications.form.audience.all': { ar: 'الكل (بما في ذلك الزوار)', en: 'All (including visitors)' },
  'admin.notifications.form.audience.users': { ar: 'المستخدمون المسجلون فقط', en: 'Registered Users Only' },
  'admin.notifications.confirm_delete': { ar: 'هل تريد حقًا حذف الإشعار "{title}"؟', en: 'Do you really want to delete the notification "{title}"?' },
  'admin.notifications.toast.updated': { ar: 'تم تحديث الإشعار', en: 'Notification updated' },
  'admin.notifications.toast.sent': { ar: 'تم إرسال الإشعار بنجاح', en: 'Notification sent successfully' },
  'admin.notifications.toast.deleted': { ar: 'تم حذف الإشعار', en: 'Notification deleted' },

  'admin.points.title': { ar: 'إدارة النقاط والشارات', en: 'Manage Points & Badges' },
  'admin.points.description': { ar: 'منح أو خصم النقاط، وإدارة قواعد الكسب.', en: 'Grant or deduct points, and manage earning rules.' },
  'admin.points.users_log': { ar: 'سجل مساهمات المستخدمين', en: 'User Contributions Log' },
  'admin.points.search_placeholder': { ar: 'ابحث بالاسم أو رقم المنزل...', en: 'Search by name or house number...' },
  'admin.points.table.user': { ar: 'المستخدم', en: 'User' },
  'admin.points.table.last_contribution': { ar: 'آخر مساهمة', en: 'Last Contribution' },
  'admin.points.table.points': { ar: 'النقاط الحالية', en: 'Current Points' },
  'admin.points.contribution_type.recycling': { ar: 'إعادة تدوير', en: 'Recycling' },
  'admin.points.contribution_type.organic': { ar: 'نفايات عضوية', en: 'Organic Waste' },
  'admin.points.contribution_type.donation': { ar: 'تبرع ملابس', en: 'Clothes Donation' },
  'admin.points.contribution_quantity.kg': { ar: '{quantity} كجم', en: '{quantity} kg' },
  'admin.points.contribution_quantity.piece': { ar: '{quantity} قطعة', en: '{quantity} pieces' },
  'admin.points.action.grant': { ar: 'منح نقاط', en: 'Grant Points' },
  'admin.points.action.deduct': { ar: 'خصم نقاط', en: 'Deduct Points' },
  'admin.points.action.grant_badge': { ar: 'منح شارة', en: 'Grant Badge' },
  'admin.points.settings.title': { ar: 'إعدادات النقاط', en: 'Points Settings' },
  'admin.points.settings.description': { ar: 'تحكم في كيفية كسب المستخدمين للنقاط.', en: 'Control how users earn points.' },
  'admin.points.settings.enable_auto': { ar: 'تفعيل منح النقاط التلقائي', en: 'Enable Automatic Point Granting' },
  'admin.points.settings.rules_title': { ar: 'قواعد كسب النقاط (لكل كجم/قطعة)', en: 'Earning Rules (per kg/item)' },
  'admin.points.settings.rule.recycling': { ar: 'إعادة تدوير (لكل كجم)', en: 'Recycling (per kg)' },
  'admin.points.settings.rule.organic': { ar: 'نفايات عضوية (لكل كجم)', en: 'Organic Waste (per kg)' },
  'admin.points.settings.rule.donation': { ar: 'تبرع ملابس (لكل قطعة)', en: 'Clothes Donation (per item)' },
  'admin.points.settings.save': { ar: 'حفظ الإعدادات', en: 'Save Settings' },
  'admin.points.dialog.grant_title': { ar: 'منح نقاط لـ {name}', en: 'Grant Points to {name}' },
  'admin.points.dialog.deduct_title': { ar: 'خصم نقاط من {name}', en: 'Deduct Points from {name}' },
  'admin.points.dialog.grant_desc': { ar: 'سيتم إضافة النقاط إلى رصيد المستخدم الحالي.', en: 'The points will be added to the user\'s current balance.' },
  'admin.points.dialog.deduct_desc': { ar: 'سيتم خصم النقاط من رصيد المستخدم الحالي.', en: 'The points will be deducted from the user\'s current balance.' },
  'admin.points.form.points_label': { ar: 'عدد النقاط', en: 'Number of Points' },
  'admin.points.form.reason_label': { ar: 'السبب (اختياري)', en: 'Reason (Optional)' },
  'admin.points.form.reason_placeholder': { ar: 'مثال: مساهمة مميزة في حملة النظافة', en: 'e.g., Outstanding contribution in cleaning campaign' },
  'admin.points.confirm_grant': { ar: 'تأكيد المنح', en: 'Confirm Grant' },
  'admin.points.confirm_deduct': { ar: 'تأكيد الخصم', en: 'Confirm Deduction' },
  'admin.points.dialog.badge_title': { ar: 'منح شارة لـ {name}', en: 'Grant Badge to {name}' },
  'admin.points.dialog.badge_desc': { ar: 'اختر الشارة التي تريد منحها لهذا المستخدم.', en: 'Choose the badge you want to grant to this user.' },
  'admin.points.form.badges_label': { ar: 'الشارات', en: 'Badges' },
  'admin.points.form.badge_placeholder': { ar: 'اختر شارة...', en: 'Select a badge...' },
  'admin.points.confirm_grant_badge': { ar: 'منح الشارة', en: 'Grant Badge' },
  'admin.points.toast.granted': { ar: 'تم منح النقاط بنجاح', en: 'Points granted successfully' },
  'admin.points.toast.deducted': { ar: 'تم خصم النقاط بنجاح', en: 'Points deducted successfully' },
  'admin.points.toast.desc': { ar: 'تم {action} {points} نقطة {preposition} {name}.', en: '{points} points have been {action} {preposition} {name}.' },
  'admin.points.toast.action.added': { ar: 'إضافة', en: 'added' },
  'admin.points.toast.action.deducted': { ar: 'خصم', en: 'deducted' },
  'admin.points.toast.preposition.to': { ar: 'إلى', en: 'to' },
  'admin.points.toast.preposition.from': { ar: 'من', en: 'from' },
  'admin.points.toast.badge_granted': { ar: 'تم منح الشارة بنجاح!', en: 'Badge granted successfully!' },
  'admin.points.toast.badge_granted_desc': { ar: 'تم منح شارة "{badgeName}" للمستخدم {userName}.', en: 'Granted "{badgeName}" badge to {userName}.' },

  'badges.beginner_recycler': { ar: 'مبتدئ التدوير', en: 'Recycling Beginner' },
  'badges.plastic_free_pioneer': { ar: 'رائد بلا بلاستيك', en: 'Plastic-Free Pioneer' },
  'badges.compost_champion': { ar: 'بطل السماد', en: 'Compost Champion' },
  'badges.waste_warrior': { ar: 'محارب النفايات', en: 'Waste Warrior' },

  'admin.redemptions.title': { ar: 'إدارة طلبات الاستبدال', en: 'Manage Redemption Requests' },
  'admin.redemptions.description': { ar: 'مراجعة طلبات المستخدمين لاستبدال النقاط بمبالغ نقدية.', en: 'Review user requests to redeem points for cash.' },
  'admin.redemptions.table.request': { ar: 'الطلب', en: 'Request' },
  'admin.redemptions.table.points_amount': { ar: 'النقاط / المبلغ', en: 'Points / Amount' },
  'admin.redemptions.table.bank_details': { ar: 'البيانات البنكية', en: 'Bank Details' },
  'admin.redemptions.points': { ar: '{count} نقطة', en: '{count} points' },
  'admin.redemptions.equivalent_to': { ar: 'تعادل {amount} ريال', en: 'Equals {amount} YER' },
  'admin.redemptions.status.pending': { ar: 'قيد التنفيذ', en: 'Pending' },
  'admin.redemptions.status.completed': { ar: 'مكتمل', en: 'Completed' },
  'admin.redemptions.status.cancelled': { ar: 'ملغي', en: 'Cancelled' },
  'admin.redemptions.toast.title': { ar: 'تم {status} الطلب', en: 'Request {status}' },
  'admin.redemptions.toast.description': { ar: 'تم تحديث حالة طلب المستخدم {user}.', en: 'Updated status for {user}\'s request.' },
  'admin.redemptions.toast.copied': { ar: 'تم نسخ رقم الحساب!', en: 'Account number copied!' },
  'admin.redemptions.confirm.approve': { ar: 'هل تؤكد إرسال المبلغ للمستخدم {user} مقابل {points} نقطة؟ سيتم خصم النقاط من رصيده.', en: 'Do you confirm sending the amount to {user} for {points} points? The points will be deducted from their balance.' },
  'admin.redemptions.confirm.deny': { ar: 'هل أنت متأكد من رفض طلب {user}؟ لن يتم خصم النقاط.', en: 'Are you sure you want to deny {user}\'s request? No points will be deducted.' },

  'admin.reports.title': { ar: 'التقارير والإحصائيات', en: 'Reports & Statistics' },
  'admin.reports.description': { ar: 'عرض الرؤى والبيانات حول أداء النظام والمستخدمين.', en: 'View insights and data about system and user performance.' },
  'admin.reports.download_button': { ar: 'تحميل التقرير الشامل (PDF)', en: 'Download Full Report (PDF)' },
  'admin.reports.generating_button': { ar: 'جارٍ الإنشاء...', en: 'Generating...' },
  'admin.reports.stats.total_users': { ar: 'إجمالي المستخدمين', en: 'Total Users' },
  'admin.reports.stats.total_donations': { ar: 'إجمالي التبرعات', en: 'Total Donations' },
  'admin.reports.stats.recycled_waste': { ar: 'النفايات المعاد تدويرها', en: 'Recycled Waste' },
  'admin.reports.stats.participation_rate': { ar: 'معدل المشاركة', en: 'Participation Rate' },
  'admin.reports.stats.change_this_month': { ar: '{value} هذا الشهر', en: '{value} this month' },
  'admin.reports.stats.stable': { ar: 'مستقر مقارنة بالشهر الماضي', en: 'Stable vs. last month' },
  'admin.reports.collection_trends.title': { ar: 'اتجاهات جمع النفايات', en: 'Waste Collection Trends' },
  'admin.reports.collection_trends.description': { ar: 'تحليل كميات النفايات المجمعة حسب النوع بمرور الوقت.', en: 'Analysis of collected waste quantities by type over time.' },
  'admin.reports.tabs.overview': { ar: 'نظرة عامة', en: 'Overview' },
  'admin.reports.tabs.users': { ar: 'المستخدمين', en: 'Users' },
  'admin.reports.tabs.waste': { ar: 'النفايات', en: 'Waste' },
  'admin.reports.tabs.financials': { ar: 'المالية', en: 'Financials' },
  'admin.reports.tabs.community': { ar: 'المجتمع', en: 'Community' },
  'admin.reports.charts.user_growth.title': { ar: 'نمو المستخدمين', en: 'User Growth' },
  'admin.reports.charts.user_growth.desc': { ar: 'عدد المستخدمين المسجلين الجدد شهريًا.', en: 'Number of new registered users per month.' },
  'admin.reports.charts.user_growth.legend': { ar: 'مستخدمون جدد', en: 'New Users' },
  'admin.reports.charts.financial.title': { ar: 'ملخص مالي', en: 'Financial Summary' },
  'admin.reports.charts.financial.desc': { ar: 'نظرة عامة على التدفقات المالية في النظام.', en: 'Overview of financial flows in the system.' },
  'admin.reports.charts.financial.support': { ar: 'الدعم المالي', en: 'Financial Support' },
  'admin.reports.charts.financial.donations': { ar: 'قيمة التبرعات', en: 'Donations Value' },
  'admin.reports.charts.financial.redemptions': { ar: 'المبالغ المستبدلة', en: 'Redemptions' },
  'admin.reports.charts.financial.amount': { ar: 'المبلغ (ريال)', en: 'Amount (YER)' },
  'admin.reports.charts.feedback.title': { ar: 'تحليل البلاغات والآراء', en: 'Feedback Analysis' },
  'admin.reports.charts.feedback.desc': { ar: 'توزيع أنواع الرسائل المستلمة من المستخدمين.', en: 'Distribution of message types received from users.' },
  'admin.reports.toast.generating_title': { ar: 'جارٍ إنشاء التقرير...', en: 'Generating Report...' },
  'admin.reports.toast.generating_desc': { ar: 'قد يستغرق هذا بضع لحظات. الرجاء الانتظار.', en: 'This may take a few moments. Please wait.' },
  'admin.reports.toast.error_title': { ar: 'خطأ', en: 'Error' },
  'admin.reports.toast.error_desc': { ar: 'حدث خطأ أثناء إنشاء ملف PDF.', en: 'An error occurred while generating the PDF.' },
  'admin.reports.toast.download_complete_title': { ar: 'اكتمل التنزيل', en: 'Download Complete' },
  'admin.reports.toast.download_complete_desc': { ar: 'تم تنزيل التقرير الشامل بنجاح.', en: 'The full report has been downloaded successfully.' },

  'admin.schedules.title': { ar: 'إدارة جداول الرفع', en: 'Manage Pickups' },
  'admin.schedules.description': { ar: 'عرض وتعديل وحذف جداول جمع النفايات.', en: 'View, edit, and delete waste collection schedules.' },
  'admin.schedules.roster.select_date': { ar: 'اختر تاريخًا', en: 'Select a date' },
  'admin.schedules.roster.download_button': { ar: 'تحميل كشف اليوم', en: 'Download Daily Roster' },
  'admin.schedules.roster.generating_button': { ar: 'جارٍ الإنشاء...', en: 'Generating...' },
  'admin.schedules.add_manual': { ar: 'إضافة جدول يدوي', en: 'Add Manual Schedule' },
  'admin.schedules.table.id': { ar: 'المعرف', en: 'ID' },
  'admin.schedules.table.user': { ar: 'المستخدم', en: 'User' },
  'admin.schedules.table.type': { ar: 'النوع', en: 'Type' },
  'admin.schedules.table.date': { ar: 'التاريخ', en: 'Date' },
  'admin.schedules.table.driver': { ar: 'السائق', en: 'Driver' },
  'admin.schedules.unassigned': { ar: 'غير معين', en: 'Unassigned' },
  'admin.schedules.status.scheduled': { ar: 'مجدول', en: 'Scheduled' },
  'admin.schedules.status.completed': { ar: 'مكتمل', en: 'Completed' },
  'admin.schedules.status.cancelled': { ar: 'ملغي', en: 'Cancelled' },
  'admin.schedules.types.recycling': { ar: 'إعادة تدوير', en: 'Recycling' },
  'admin.schedules.types.general': { ar: 'نفايات عامة', en: 'General Waste' },
  'admin.schedules.types.bulky': { ar: 'مواد كبيرة', en: 'Bulky Items' },
  'admin.schedules.types.organic': { ar: 'نفايات عضوية', en: 'Organic Waste' },
  'admin.schedules.confirm_delete': { ar: 'هل تريد حقًا حذف الجدول رقم {id}؟', en: 'Do you really want to delete schedule #{id}?' },
  'admin.schedules.dialog.edit_title': { ar: 'تعديل جدول الرفع', en: 'Edit Pickup Schedule' },
  'admin.schedules.dialog.add_title': { ar: 'إضافة جدول رفع يدوي', en: 'Add Manual Pickup Schedule' },
  'admin.schedules.dialog.edit_desc': { ar: 'تعديل تفاصيل طلب الرفع الحالي.', en: 'Modify the details of the current pickup request.' },
  'admin.schedules.dialog.add_desc': { ar: 'إنشاء طلب رفع جديد لمستخدم معين.', en: 'Create a new pickup request for a specific user.' },
  'admin.schedules.form.user': { ar: 'اسم المستخدم', en: 'User Name' },
  'admin.schedules.form.house_number': { ar: 'رقم المنزل', en: 'House Number' },
  'admin.schedules.form.address': { ar: 'العنوان التفصيلي', en: 'Detailed Address' },
  'admin.schedules.form.address_placeholder': { ar: 'مثال: حي السلام، شارع 5، منزل رقم 12', en: 'e.g., Al-Salam District, St 5, House 12' },
  'admin.schedules.form.gmaps_link': { ar: 'رابط خرائط جوجل', en: 'Google Maps Link' },
  'admin.schedules.form.waste_type': { ar: 'نوع النفايات', en: 'Waste Type' },
  'admin.schedules.form.waste_type_placeholder': { ar: 'اختر نوعًا...', en: 'Select a type...' },
  'admin.schedules.form.pickup_date': { ar: 'تاريخ الرفع', en: 'Pickup Date' },
  'admin.schedules.form.select_date': { ar: 'اختر تاريخًا', en: 'Select a date' },
  'admin.schedules.form.assigned_driver': { ar: 'السائق المعين (اختياري)', en: 'Assigned Driver (Optional)' },
  'admin.schedules.form.driver_name': { ar: 'اسم السائق', en: 'Driver Name' },
  'admin.schedules.form.driver_phone': { ar: 'رقم هاتف السائق', en: 'Driver Phone Number' },
  'admin.schedules.form.status_placeholder': { ar: 'اختر حالة...', en: 'Select a status...' },
  'admin.schedules.toast.updated': { ar: 'تم تحديث الجدول بنجاح', en: 'Schedule updated successfully' },
  'admin.schedules.toast.added': { ar: 'تمت إضافة الجدول بنجاح', en: 'Schedule added successfully' },
  'admin.schedules.toast.deleted': { ar: 'تم حذف الجدول بنجاح', en: 'Schedule deleted successfully' },
  'admin.schedules.roster.none_title': { ar: 'لا توجد جداول', en: 'No Schedules' },
  'admin.schedules.roster.none_desc': { ar: 'لا توجد جداول رفع لهذا اليوم.', en: 'There are no pickup schedules for this date.' },
  'admin.schedules.roster.generating_title': { ar: 'جارٍ إنشاء الكشف...', en: 'Generating Roster...' },
  'admin.schedules.roster.generating_desc': { ar: 'الرجاء الانتظار قليلاً.', en: 'Please wait a moment.' },
  'admin.schedules.roster.error_title': { ar: 'خطأ', en: 'Error' },
  'admin.schedules.roster.error_desc': { ar: 'حدث خطأ أثناء إنشاء الملف.', en: 'An error occurred while generating the file.' },
  'admin.schedules.roster.download_complete_title': { ar: 'اكتمل التنزيل', en: 'Download Complete' },
  'admin.schedules.roster.download_complete_desc': { ar: 'تم تنزيل كشف جمع النفايات بنجاح.', en: 'The waste collection roster has been downloaded.' },

  'admin.users.title': { ar: 'إدارة المستخدمين', en: 'Manage Users' },
  'admin.users.description': { ar: 'إضافة وتعديل وحذف المستخدمين وأدوارهم في النظام.', en: 'Add, edit, and delete users and their roles in the system.' },
  'admin.users.search_placeholder': { ar: 'ابحث بالاسم أو البريد الإلكتروني...', en: 'Search by name or email...' },
  'admin.users.add_new': { ar: 'إضافة مستخدم جديد', en: 'Add New User' },
  'admin.users.table.user': { ar: 'المستخدم', en: 'User' },
  'admin.users.table.role': { ar: 'الدور', en: 'Role' },
  'admin.users.table.id': { ar: 'معرف المستخدم', en: 'User ID' },
  'admin.users.role.user': { ar: 'مستخدم', en: 'User' },
  'admin.users.role.admin': { ar: 'مدير', en: 'Admin' },
  'admin.users.confirm_delete': { ar: 'هل تريد حقًا حذف المستخدم {name}؟ سيتم حذف جميع بياناته.', en: 'Do you really want to delete the user {name}? All their data will be removed.' },
  'admin.users.dialog.edit_title': { ar: 'تعديل مستخدم', en: 'Edit User' },
  'admin.users.dialog.add_title': { ar: 'إضافة مستخدم جديد', en: 'Add New User' },
  'admin.users.dialog.edit_desc': { ar: 'تعديل بيانات المستخدم والدور الخاص به.', en: 'Modify user data and their role.' },
  'admin.users.dialog.add_desc': { ar: 'إنشاء حساب مستخدم جديد في النظام.', en: 'Create a new user account in the system.' },
  'admin.users.form.name': { ar: 'الاسم الكامل', en: 'Full Name' },
  'admin.users.form.email': { ar: 'البريد الإلكتروني', en: 'Email Address' },
  'admin.users.form.role': { ar: 'الدور', en: 'Role' },
  'admin.users.form.role_placeholder': { ar: 'اختر دورًا...', en: 'Select a role...' },
  'admin.users.toast.deleted': { ar: 'تم حذف المستخدم بنجاح', en: 'User deleted successfully' },
  'admin.users.toast.updated': { ar: 'تم تحديث المستخدم بنجاح', en: 'User updated successfully' },
  'admin.users.toast.added': { ar: 'تمت إضافة المستخدم بنجاح', en: 'User added successfully' },

  'admin.vouchers.title': { ar: 'إدارة قسائم المكافآت', en: 'Manage Reward Vouchers' },
  'admin.vouchers.description': { ar: 'إنشاء وتعديل القسائم التي يمكن للمستخدمين استبدالها بنقاطهم.', en: 'Create and edit vouchers that users can redeem with their points.' },
  'admin.vouchers.add_new': { ar: 'إضافة قسيمة جديدة', en: 'Add New Voucher' },
  'admin.vouchers.table.partner': { ar: 'الشريك', en: 'Partner' },
  'admin.vouchers.table.voucher': { ar: 'القسيمة', en: 'Voucher' },
  'admin.vouchers.table.points': { ar: 'النقاط المطلوبة', en: 'Points Required' },
  'admin.vouchers.table.quantity': { ar: 'الكمية المتبقية', en: 'Quantity Left' },
  'admin.vouchers.status.active': { ar: 'نشط', en: 'Active' },
  'admin.vouchers.status.inactive': { ar: 'غير نشط', en: 'Inactive' },
  'admin.vouchers.confirm_delete': { ar: 'هل تريد حقًا حذف قسيمة "{title}"؟', en: 'Do you really want to delete the voucher "{title}"?' },
  'admin.vouchers.dialog.edit_title': { ar: 'تعديل قسيمة', en: 'Edit Voucher' },
  'admin.vouchers.dialog.add_title': { ar: 'إضافة قسيمة جديدة', en: 'Add New Voucher' },
  'admin.vouchers.form.logo': { ar: 'شعار الشريك', en: 'Partner Logo' },
  'admin.vouchers.form.logo_preview': { ar: 'معاينة الشعار', en: 'Logo Preview' },
  'admin.vouchers.form.upload_instruction': { ar: 'انقر للتحميل أو اسحب الصورة هنا', en: 'Click to upload or drag image here' },
  'admin.vouchers.form.partner_name': { ar: 'اسم الشريك', en: 'Partner Name' },
  'admin.vouchers.form.partner_placeholder': { ar: 'مثال: المقهى الأخضر', en: 'e.g., The Green Cafe' },
  'admin.vouchers.form.voucher_title': { ar: 'عنوان القسيمة', en: 'Voucher Title' },
  'admin.vouchers.form.title_placeholder': { ar: 'مثال: خصم 10%', en: 'e.g., 10% Discount' },
  'admin.vouchers.form.description': { ar: 'وصف القسيمة', en: 'Voucher Description' },
  'admin.vouchers.form.description_placeholder': { ar: 'شرح موجز عن القسيمة وشروطها.', en: 'A brief explanation of the voucher and its terms.' },
  'admin.vouchers.form.points': { ar: 'النقاط المطلوبة', en: 'Points Required' },
  'admin.vouchers.form.quantity': { ar: 'الكمية المتاحة', en: 'Available Quantity' },
  'admin.vouchers.form.status_placeholder': { ar: 'اختر حالة...', en: 'Select a status...' },
  'admin.vouchers.toast.updated': { ar: 'تم تحديث القسيمة بنجاح', en: 'Voucher updated successfully' },
  'admin.vouchers.toast.added': { ar: 'تمت إضافة القسيمة بنجاح', en: 'Voucher added successfully' },
  'admin.vouchers.toast.deleted': { ar: 'تم حذف القسيمة', en: 'Voucher deleted' },
    'admin.vouchers.tabs.manage': { ar: 'إدارة القسائم', en: 'Manage Vouchers' },
    'admin.vouchers.tabs.requests': { ar: 'طلبات الاستبدال', en: 'Redemption Requests' },
    'admin.vouchers.requests.title': { ar: 'طلبات استبدال القسائم', en: 'Voucher Redemption Requests' },
    'admin.vouchers.requests.description': { ar: 'مراجعة طلبات المستخدمين للقسائم وإرسال أكوادهم.', en: 'Review user requests for vouchers and send their codes.' },
    'admin.vouchers.requests.table.user': { ar: 'المستخدم', en: 'User' },
    'admin.vouchers.requests.table.voucher': { ar: 'القسيمة المطلوبة', en: 'Requested Voucher' },
    'admin.vouchers.requests.table.date': { ar: 'تاريخ الطلب', en: 'Request Date' },
    'admin.vouchers.requests.status.pending': { ar: 'قيد المراجعة', en: 'Pending' },
    'admin.vouchers.requests.status.completed': { ar: 'مكتمل', en: 'Completed' },
    'admin.vouchers.requests.action.process': { ar: 'معالجة الطلب', en: 'Process Request' },
    'admin.vouchers.process_dialog.title': { ar: 'معالجة طلب قسيمة', en: 'Process Voucher Request' },
    'admin.vouchers.process_dialog.description': { ar: 'أنت تقوم بمعالجة طلب قسيمة "{voucherTitle}" للمستخدم {userName}.', en: 'You are processing a request for voucher "{voucherTitle}" for user {userName}.' },
    'admin.vouchers.process_dialog.coupon_label': { ar: 'كود القسيمة', en: 'Coupon Code' },
    'admin.vouchers.process_dialog.coupon_placeholder': { ar: 'أدخل كود القسيمة هنا', en: 'Enter the coupon code here' },
    'admin.vouchers.process_dialog.button': { ar: 'إرسال وإكمال', en: 'Send & Complete' },
    'admin.vouchers.toast.processed_title': { ar: 'تمت معالجة الطلب', en: 'Request Processed' },
    'admin.vouchers.toast.processed_desc': { ar: 'تم إكمال الطلب وإرسال الكود للمستخدم.', en: 'The request has been completed and the code sent to the user.' },


  'classify.image.title': { ar: 'صنف بالصورة', en: 'Classify by Image' },
  'classify.image.description': { ar: 'التقط صورة أو ارفعها ليقوم الذكاء الاصطناعي بتصنيفها.', en: 'Take or upload a photo for the AI to classify.' },
  'classify.image.preview_alt': { ar: 'معاينة الصورة المرفوعة', en: 'Uploaded image preview' },
  'classify.image.upload_instruction': { ar: 'انقر لاختيار صورة', en: 'Click to select an image' },
  'classify.image.selected_file': { ar: 'الملف المحدد', en: 'Selected file' },
  'classify.image.classify_button': { ar: 'تصنيف الآن', en: 'Classify Now' },
  'classify.image.classifying_button': { ar: 'جارٍ التصنيف...', en: 'Classifying...' },
  'classify.result.title': { ar: 'نتيجة التصنيف', en: 'Classification Result' },
  'classify.result.type': { ar: 'نوع المخلفات', en: 'Waste Type' },
  'classify.result.confidence': { ar: 'مستوى الثقة', en: 'Confidence Level' },
  'classify.result.instructions': { ar: 'تعليمات التخلص', en: 'Disposal Instructions' },
  'classify.guides.title': { ar: 'أدلة التصنيف', en: 'Classification Guides' },
  'classify.guides.description': { ar: 'اختر نوعًا للحصول على دليل مفصل.', en: 'Select a type to get a detailed guide.' },
  'classify.guides.generating_title': { ar: 'جارٍ إنشاء الدليل...', en: 'Generating Guide...' },
  'classify.guides.guide_for': { ar: 'دليل تصنيف: {item}', en: 'Classification Guide: {item}' },
  'classify.guides.generating_desc': { ar: 'يقوم مساعدنا الذكي بإعداد دليلك الآن.', en: 'Our AI assistant is preparing your guide.' },
  'classify.toast.no_file_title': { ar: 'لم يتم اختيار ملف', en: 'No File Selected' },
  'classify.toast.no_file_desc': { ar: 'الرجاء اختيار صورة أولاً.', en: 'Please select an image first.' },
  'classify.toast.failed_title': { ar: 'فشل التصنيف', en: 'Classification Failed' },
  'classify.toast.failed_desc': { ar: 'حدث خطأ أثناء محاولة تصنيف الصورة.', en: 'An error occurred while trying to classify the image.' },
  'classify.toast.guide_failed_title': { ar: 'فشل جلب الدليل', en: 'Failed to Fetch Guide' },
  'classify.toast.guide_failed_desc': { ar: 'لم نتمكن من إنشاء الدليل. الرجاء المحاولة مرة أخرى.', en: 'We couldn\'t generate the guide. Please try again.' },
  'classify.types.glass': { ar: 'زجاج', en: 'Glass' },
  'classify.types.paper': { ar: 'ورق', en: 'Paper' },
  'classify.types.plastic': { ar: 'بلاستيك', en: 'Plastic' },
  'classify.types.ewaste': { ar: 'نفايات إلكترونية', en: 'E-Waste' },
  'classify.types.organic': { ar: 'عضوي', en: 'Organic' },
  'classify.types.metal': { ar: 'معدن', en: 'Metal' },
  'classify.types.garden': { ar: 'نفايات حدائق', en: 'Garden Waste' },
  'classify.types.construction': { ar: 'مخلفات بناء', en: 'Construction Debris' },

  'contact.title': { ar: 'تواصل معنا', en: 'Contact Us' },
  'contact.description': { ar: 'نحن هنا للاستماع إليك. شاركنا بلاغاتك، شكاواك، أو اقتراحاتك.', en: 'We are here to listen. Share your reports, complaints, or suggestions.' },
  'contact.form.type_label': { ar: 'نوع الرسالة', en: 'Message Type' },
  'contact.form.type_placeholder': { ar: 'اختر نوع الرسالة...', en: 'Select message type...' },
  'contact.form.subject_label': { ar: 'الموضوع', en: 'Subject' },
  'contact.form.subject_placeholder': { ar: 'مثال: حاوية ممتلئة في الحي ', en: 'e.g., Full container in the neighborhood' },
  'contact.form.details_label': { ar: 'التفاصيل', en: 'Details' },
  'contact.form.details_placeholder': { ar: 'يرجى تقديم أكبر قدر ممكن من التفاصيل...', en: 'Please provide as much detail as possible...' },
  'contact.form.photo_label': { ar: 'إرفاق صورة (اختياري)', en: 'Attach Photo (Optional)' },
  'contact.form.photo_preview_alt': { ar: 'معاينة الصورة المرفقة', en: 'Attached photo preview' },
  'contact.form.upload_instruction': { ar: 'انقر أو اسحب صورة إلى هنا', en: 'Click or drag a photo here' },
  'contact.form.send_button': { ar: 'إرسال الرسالة', en: 'Send Message' },
  'contact.toast.success_title': { ar: 'تم استلام رسالتك!', en: 'Message Received!' },
  'contact.toast.success_desc': { ar: 'شكراً لك. سنقوم بمراجعة رسالتك والرد عليك قريباً.', en: 'Thank you. We will review your message and get back to you soon.' },

  'donate.title': { ar: ' تبرع بالملابس عبر وصــال', en: 'Donate Clothes By Wesal' },
  'donate.description': { ar: 'ساهم في رسم البسمة على وجوه الآخرين بتبرعك.', en: 'Contribute to bringing smiles to others with your donation.' },
  'donate.image_alt': { ar: 'صورة لملابس جاهزة للتبرع', en: 'Image of clothes ready for donation' },
  'donate.form.type_label': { ar: 'نوع الملابس', en: 'Clothing Type' },
  'donate.form.type_placeholder': { ar: 'اختر النوع...', en: 'Select type...' },
  'donate.form.condition_label': { ar: 'حالة الملابس', en: 'Clothing Condition' },
  'donate.form.condition_placeholder': { ar: 'اختر الحالة...', en: 'Select condition...' },
  'donate.form.quantity_label': { ar: 'الكمية (تقريبي)', en: 'Quantity (Approximate)' },
  'donate.form.address_label': { ar: 'عنوان الاستلام', en: 'Pickup Address' },
  'donate.form.address_placeholder': { ar: 'يرجى كتابة العنوان بوضوح لتسهيل وصول المندوب...', en: 'Please write the address clearly to help the agent...' },
  'donate.form.notes_label': { ar: 'ملاحظات إضافية (اختياري)', en: 'Additional Notes (Optional)' },
  'donate.form.notes_placeholder': { ar: 'أي تفاصيل أخرى تود إضافتها...', en: 'Any other details you wish to add...' },
  'donate.form.send_button': { ar: 'إرسال طلب التبرع', en: 'Send Donation Request' },
  'donate.toast.success_title': { ar: 'تم استلام طلبك!', en: 'Request Received!' },
  'donate.toast.success_desc': { ar: 'شكراً لتبرعك السخي. سيتم التواصل معك لتنسيق عملية الاستلام.', en: 'Thank you for your generous donation. We will contact you to coordinate the pickup.' },

  'forgot_password.title': { ar: 'نسيت كلمة المرور؟', en: 'Forgot Password?' },
  'forgot_password.submitted_desc': { ar: 'عند تسجيل الدخول قم بتغيير كلمة المرور فورا.', en: 'You have to change your password after you log in.' },
  'forgot_password.initial_desc': { ar: 'لا تقلق، يحدث ذلك. أدخل ايميلك وسنعرض لك كلمة مرور .', en: 'No worries, it happens. Enter your email and we\'ll show your password.' },
  'forgot_password.your_password': { ar: 'كلمة المرور الخاصة بك', en: 'Your  Password' },
  'forgot_password.demo_notice': { ar: ' قم بنسخها واستخدمها لتسجيل الدخول.', en: ' Copy it and use it to log in.' },
  'forgot_password.phone_label': { ar: 'رقم الهاتف', en: 'Phone Number' },
  'forgot_password.submit_button': { ar: 'عرض كلمة المرور', en: 'Show Password' },
  'forgot_password.back_to_login': { ar: 'العودة لتسجيل الدخول', en: 'Back to Login' },
  'forgot_password.toast.copied_title': { ar: 'تم النسخ!', en: 'Copied!' },
  'forgot_password.toast.copied_desc': { ar: 'تم نسخ كلمة المرور إلى الحافظة.', en: 'Password copied to clipboard.' },

  'help.title': { ar: 'مركز المساعدة', en: 'Help Center' },
  'help.description': { ar: 'ابحث عن إجابات لأسئلتك الشائعة هنا.', en: 'Find answers to your frequently asked questions here.' },
  'help.faq1.question': { ar: 'كيف أجدول عملية رفع نفايات؟', en: 'How do I schedule a waste pickup?' },
  'help.faq1.answer': { ar: 'اذهب إلى صفحة "جدولة الرفع"، اختر نوع وكمية النفايات، حدد تاريخًا مناسبًا، ثم أكد الطلب.', en: 'Go to the "Schedule Pickup" page, select the type and quantity of waste, choose a suitable date, and confirm the request.' },
  'help.faq2.question': { ar: 'كيف أكسب النقاط؟', en: 'How do I earn points?' },
  'help.faq2.answer': { ar: 'تكسب نقاطًا مقابل كل عملية إعادة تدوير ناجحة، تبرع بالملابس، أو المشاركة في حملات النظافة المجتمعية.', en: 'You earn points for every successful recycling pickup, clothes donation, or participation in community clean-up campaigns.' },
  'help.faq3.question': { ar: 'ماذا أفعل إذا فاتتني عملية الرفع؟', en: 'What if I miss a pickup?' },
  'help.faq3.answer': { ar: 'يمكنك إعادة جدولة الرفع لليوم التالي المتاح من خلال صفحة "جدولة الرفع". حاول إخراج حاوياتك في الوقت المحدد لتجنب ذلك.', en: 'You can reschedule the pickup for the next available day from the "Schedule Pickup" page. Try to take out your bins on time to avoid this.' },
  'help.faq4.question': { ar: 'كيف يمكنني استبدال نقاطي؟', en: 'How can I redeem my points?' },
  'help.faq4.answer': { ar: 'من صفحة "المكافآت والنقاط"، يمكنك استبدال نقاطك بمبالغ نقدية أو قسائم خصم من شركائنا.', en: 'From the "Rewards & Points" page, you can redeem your points for cash or discount vouchers from our partners.' },
  'help.faq5.question': { ar: 'هل يمكنني التبرع بأشياء أخرى غير الملابس؟', en: 'Can I donate items other than clothes?' },
  'help.faq5.answer': { ar: 'حاليًا، نظام التبرعات مخصص للملابس فقط. نحن نعمل على توسيع هذا الخيار في المستقبل.', en: 'Currently, the donation system is only for clothes. We are working on expanding this option in the future.' },
  'help.faq6.question': { ar: 'كيف يمكنني أن أصبح متطوعًا؟', en: 'How can I become a volunteer?' },
  'help.faq6.answer': { ar: 'يسعدنا اهتمامك! يمكنك التواصل معنا عبر صفحة "البلاغات والاقتراحات" وإبداء رغبتك في التطوع.', en: 'We are delighted by your interest! You can contact us through the "Feedback & Suggestions" page and express your desire to volunteer.' },
  'help.faq7.question': { ar: 'لم أجد إجابة لسؤالي، ماذا أفعل؟', en: 'I didn\'t find an answer to my question, what should I do?' },
  'help.faq7.answer': { ar: 'لا تتردد في التواصل معنا مباشرة عبر صفحة "البلاغات والاقتراحات" وسيقوم فريقنا بمساعدتك.', en: 'Feel free to contact us directly through the "Feedback & Suggestions" page, and our team will assist you.' },

  'history.title': { ar: 'سجل عمليات الرفع', en: 'Pickup History' },
  'history.description': { ar: 'هنا يمكنك تتبع جميع عمليات الرفع السابقة وحالاتها.', en: 'Here you can track all your past pickups and their statuses.' },
  'history.download_button': { ar: 'تحميل التقرير', en: 'Download Report' },
  'history.pickup_type': { ar: 'رفع {type}', en: '{type} Pickup' },
  'history.points': { ar: '{count} نقطة', en: '{count} points' },
  'history.status.completed': { ar: 'مكتمل', en: 'Completed' },
  'history.status.scheduled': { ar: 'مجدول', en: 'Scheduled' },
  'history.status.cancelled': { ar: 'ملغي', en: 'Cancelled' },
  'history.status.missed': { ar: 'فاتك - لم تكن بالخارج', en: 'Missed - Not outside' },

  'map.title': { ar: 'خريطة الحاويات', en: 'Container Map' },
  'map.description': { ar: 'ابحث عن أقرب حاوية نفايات في منطقتك.', en: 'Find the nearest waste container in your area.' },
  'map.get_directions': { ar: 'احصل على الاتجاهات', en: 'Get Directions' },
  'map.public_bin': { ar: 'حاوية عامة', en: 'Public Bin' },

  'news.title': { ar: 'أخبار وفعاليات', en: 'News & Events' },
  'news.description': { ar: 'ابق على اطلاع بآخر أخبارنا وحملاتنا ومبادراتنا المجتمعية.', en: 'Stay updated with our latest news, campaigns, and community initiatives.' },
  'news.read_more': { ar: 'اقرأ المزيد', en: 'Read More' },
  'news.article1.title': { ar: 'حملة "نظف حيك" تحقق نجاحًا كبيرًا', en: '"Clean Your Neighborhood" Campaign a Great Success' },
  'news.article1.excerpt': { ar: 'شارك أكثر من 200 متطوع في حملتنا الأخيرة، مما أسفر عن جمع 5 أطنان من المواد القابلة لإعادة التدوير.', en: 'Over 200 volunteers participated in our latest campaign, resulting in the collection of 5 tons of recyclable materials.' },
  'news.article1.author': { ar: 'فريق نظف حيك', en: 'Nadhif Hayak Team' },
  'news.article2.title': { ar: 'إطلاق برنامج جديد لمكافآت إعادة التدوير', en: 'New Recycling Rewards Program Launched' },
  'news.article2.excerpt': { ar: 'نقدم لكم نظام النقاط الجديد! كلما قمت بإعادة تدوير أكثر، زادت نقاطك التي يمكنك استبدالها بجوائز قيمة.', en: 'Introducing our new points system! The more you recycle, the more points you earn to redeem for great prizes.' },
  'news.article2.author': { ar: 'إدارة المشروع', en: 'Project Management' },
  'news.article3.title': { ar: 'ورشة عمل حول صناعة السماد المنزلي', en: 'Workshop on Home Composting' },
  'news.article3.excerpt': { ar: 'تعلم كيفية تحويل بقايا مطبخك إلى سماد غني لحديقتك في ورشة العمل القادمة.', en: 'Learn how to turn your kitchen scraps into rich compost for your garden in our upcoming workshop.' },
  'news.article3.author': { ar: 'قسم البيئة', en: 'Environment Dept.' },
  'news.article4.title': { ar: 'يوم خاص لجمع النفايات الإلكترونية', en: 'Special E-Waste Collection Day' },
  'news.article4.excerpt': { ar: 'لا ترمي أجهزتك القديمة! أحضرها إلى نقطة الجمع المخصصة يوم السبت القادم للتخلص الآمن منها.', en: 'Don\'t throw away your old gadgets! Bring them to our special collection point next Saturday for safe disposal.' },
  'news.article4.author': { ar: 'فريق العمليات', en: 'Operations Team' },

  'rewards.stats.total_points': { ar: 'إجمالي النقاط', en: 'Total Points' },
  'rewards.stats.keep_it_up': { ar: 'استمر في العمل الرائع!', en: 'Keep up the great work!' },
  'rewards.my_badges': { ar: 'شاراتي المكتسبة', en: 'My Earned Badges' },
  'rewards.badges_desc': { ar: 'هذه هي الشارات التي حصلت عليها لمساهماتك.', en: 'These are the badges you\'ve earned for your contributions.' },
  'rewards.redeem.title': { ar: 'استبدال النقاط بمبالغ نقدية', en: 'Redeem Points for Cash' },
  'rewards.redeem.description': { ar: 'حوّل نقاطك التي كسبتها بجد إلى نقود حقيقية.', en: 'Turn your hard-earned points into real money.' },
  'rewards.redeem.rate': { ar: '1 نقطة = 2 ريال', en: '1 Point = 2 YER' },
  'rewards.redeem.rate_desc': { ar: 'هذا هو سعر الصرف الحالي للنقاط.', en: 'This is the current exchange rate for points.' },
  'rewards.redeem.how_it_works_title': { ar: 'كيف يعمل؟', en: 'How It Works?' },
  'rewards.redeem.how_it_works_desc': { ar: 'عند تقديم الطلب، سنقوم بمراجعته وتحويل المبلغ إلى حسابك البنكي خلال 7 أيام عمل.', en: 'When you submit a request, we will review it and transfer the amount to your bank account within 7 business days.' },
  'rewards.redeem.redeem_button': { ar: 'تقديم طلب استبدال الآن', en: 'Submit Redemption Request Now' },
  'rewards.vouchers.title': { ar: 'استبدال النقاط بقسائم', en: 'Redeem Points for Vouchers' },
  'rewards.vouchers.description': { ar: 'استخدم نقاطك للحصول على خصومات من شركائنا.', en: 'Use your points to get discounts from our partners.' },
    'rewards.vouchers.redeem_button': { ar: 'استبدال', en: 'Redeem' },
    'rewards.vouchers.points_label': { ar: 'نقطة', en: 'Points' },
    'rewards.vouchers.none_available': { ar: 'لا توجد قسائم متاحة حاليًا. تحقق مرة أخرى قريبًا!', en: 'No vouchers available right now. Check back soon!' },
    'rewards.redeem.voucher_dialog_title': { ar: 'تأكيد استبدال القسيمة', en: 'Confirm Voucher Redemption' },
    'rewards.redeem.voucher_dialog_desc': { ar: 'هل تريد حقًا استبدال {points} نقطة مقابل قسيمة "{title}"؟', en: 'Are you sure you want to redeem {points} points for the "{title}" voucher?' },
    'rewards.redeem.voucher_toast_success': { ar: 'تم استبدال القسيمة بنجاح!', en: 'Voucher redeemed successfully!' },
    'rewards.redeem.voucher_toast_fail': { ar: 'فشل استبدال القسيمة.', en: 'Voucher redemption failed.' },
  'rewards.leaderboard.title': { ar: 'قائمة المتصدرين', en: 'Leaderboard' },
  'rewards.leaderboard.description': { ar: 'شاهد ترتيبك بين أكثر المستخدمين مساهمة في الحي.', en: 'See your rank among the top contributors in the neighborhood.' },
  'rewards.leaderboard.rank': { ar: 'الترتيب', en: 'Rank' },
  'rewards.leaderboard.user': { ar: 'المستخدم', en: 'User' },
  'rewards.leaderboard.points': { ar: 'النقاط', en: 'Points' },
  'rewards.leaderboard.best': { ar: 'الأفضل!', en: 'Best!' },
  'rewards.redeem.dialog.title': { ar: 'تأكيد طلب الاستبدال', en: 'Confirm Redemption Request' },
  'rewards.redeem.dialog.description': { ar: 'أنت على وشك استبدال {points} نقطة بمبلغ {amount} ريال. الرجاء إدخال بيانات حسابك البنكي.', en: 'You are about to redeem {points} points for {amount} YER. Please enter your bank account details.' },
  'rewards.redeem.form.account_holder': { ar: 'اسم صاحب الحساب', en: 'Account Holder Name' },
  'rewards.redeem.form.account_holder_placeholder': { ar: 'الاسم كما هو مسجل في البنك', en: 'Name as registered with the bank' },
  'rewards.redeem.form.bank_name': { ar: 'اسم البنك', en: 'Bank Name' },
  'rewards.redeem.form.bank_name_placeholder': { ar: 'اختر بنكًا', en: 'Select a bank' },
  'rewards.redeem.form.account_number': { ar: 'رقم الحساب', en: 'Account Number' },
  'rewards.redeem.form.confirm_button': { ar: 'تأكيد الطلب', en: 'Confirm Request' },
  'rewards.redeem.toast.success_title': { ar: 'تم استلام طلبك!', en: 'Request Received!' },
  'rewards.redeem.toast.success_desc': { ar: 'ستتم معالجة طلب الاستبدال الخاص بك قريبًا.', en: 'Your redemption request will be processed soon.' },

  'support.title': { ar: 'ادعم مشروعنا', en: 'Support Our Project' },
  'support.description': { ar: 'دعمك المالي يساعدنا على الاستمرار والتوسع في خدماتنا.', en: 'Your financial support helps us continue and expand our services.' },
  'support.bank_accounts_title': { ar: 'حساباتنا البنكية', en: 'Our Bank Accounts' },
  'support.form_instructions': { ar: 'بعد التحويل، يرجى ملء النموذج على اليسار وتأكيد عملية الدعم.', en: 'After transferring, please fill out the form on the left to confirm your support.' },
  'support.form.donor_name': { ar: 'اسم الداعم', en: 'Donor\'s Name' },
  'support.form.donor_name_placeholder': { ar: 'الاسم الذي تم التحويل به', en: 'The name used for the transfer' },
  'support.form.amount_label': { ar: 'المبلغ المحول (بالريال)', en: 'Amount Transferred (YER)' },
  'support.form.bank_label': { ar: 'البنك الذي تم التحويل إليه', en: 'Bank Transferred To' },
  'support.form.bank_placeholder': { ar: 'اختر البنك...', en: 'Select the bank...' },
  'support.form.receipt_label': { ar: 'إرفاق إيصال التحويل', en: 'Attach Transfer Receipt' },
  'support.form.receipt_preview_alt': { ar: 'معاينة الإيصال', en: 'Receipt Preview' },
  'support.form.upload_instruction': { ar: 'انقر أو اسحب صورة الإيصال هنا', en: 'Click or drag receipt image here' },
  'support.form.submit_button': { ar: 'تأكيد الدعم', en: 'Confirm Support' },
  'support.toast.copied_title': { ar: 'تم النسخ', en: 'Copied' },
  'support.toast.copied_desc': { ar: 'تم نسخ رقم الحساب إلى الحافظة.', en: 'Account number copied to clipboard.' },
  'support.toast.success_title': { ar: 'شكراً لدعمك!', en: 'Thank You for Your Support!' },
  'support.toast.success_desc': { ar: 'لقد تم استلام تأكيدك وسنقوم بمراجعته.', en: 'We have received your confirmation and will review it.' },
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = React.useState<Language>('ar');

  React.useEffect(() => {
    const storedLang = localStorage.getItem('language') as Language | null;
    const initialLang = storedLang && ['ar', 'en'].includes(storedLang) ? storedLang : 'ar';
    setLanguageState(initialLang);
    document.documentElement.lang = initialLang;
    document.documentElement.dir = initialLang === 'ar' ? 'rtl' : 'ltr';
  }, []);

  const setLanguage = React.useCallback((lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
    document.documentElement.lang = lang;
    document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
  }, []);

  const t = React.useCallback((key: string, options?: { [key: string]: string | number | undefined }): string => {
    let translation = translations[key]?.[language] || key;
    if (options) {
      Object.keys(options).forEach(optionKey => {
        const value = options[optionKey];
        if (value !== undefined) {
          const regex = new RegExp(`{${optionKey}}`, 'g');
          translation = translation.replace(regex, String(value));
        }
      });
    }
    return translation;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = React.useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
